### ISSUE TITLE
Does anyone use -p flag?

### ISSUE THREAD

**Issue by dmitshur** [sqs/rego#4]
@shurcooL referenced [**main.go:23-L29**](https://github.com/sqs/rego/blob/7e836f8446993a92ac4a6ad7f390f84f588acdb1/rego.go#L23-L29):

``` Go
// otherPkgs lets you specify other packages that will also be
// installed when the watched files change. This lets you work
// around an annoyance where godep does not rebuild stale vendored
// dependencies when their sources change (see
// https://github.com/tools/godep/issues/45#issuecomment-73411554);
// you just need to specify any vendored package in this flag.
otherPkgs = flag.String("p", "", "also `go install` these other pkgs (comma-separated import paths)")
```

---

The comment refers to [an issue](https://github.com/tools/godep/issues/45) that has since been resolved with the release of Go 1.5.

Go will no longer use stale pkg cache from Godep workspace when the source has changed; it will always use the latest source.

Does anyone use/rely on this feature for any other reason anymore?

If not, perhaps it can be removed since it's no longer relevant.

**Comment by sqs** [comment]
When Go 1.4 is no longer being used by us, let's remove it.

**Comment by dmitshur** [comment]
We're on Go 1.6 now, so I don't think Go 1.4 is used by us. We're not even using `godep` to build anymore.

I've created #9 since I already had the commit for it locally from a while ago.
